routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'register' => false,
]);

// Change password
Route::get('password-change', 'Auth\PasswordController@changePassword')->name('password.change');
Route::post('password-change', 'Auth\PasswordController@postChangePassword');

// Home page
Route::get('/', 'HomeController@index')->name('home');

// Product management
Route::resource('products', 'ProductController')->middleware('auth');

// Tracking
Route::resource('tracking', 'TrackingController')->middleware('auth');

// Control Panel
Route::resource('users', 'UserController')->middleware('auth');

// File holder
Route::post('files', 'FileController@store')->middleware('auth');


Route::get('reports/chart-quantity', 'ReportController@chartQuantity')->middleware('auth');
Route::get('reports/top-customers', 'ReportController@topCustomers')->middleware('auth');
Route::get('reports/top-products', 'ReportController@topProducts')->middleware('auth');

Route::get('reports/low-prod', 'ReportController@lowProdudct')->middleware('auth'); //ปั่น

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * Class User
 * @package App
 * @property string $role_id
 */
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isAdmin()
    {
        return $this->role_id === 'admin';
    }
}

app/Http/Controllers/UserController.php
<?php namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;

class UserController extends Controller
{

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $users = User::query()->orderByDesc('id')->paginate();

        return view('users.index', compact('users'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create(Request $request)
    {
        $this->authorize('create', User::class);

        return view('users.create');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('create', User::class);

        $data = $request->validate([
            'email' => ['required', 'email', Rule::unique('users', 'email')],
            'name' => 'required|max:100',
            'password' => 'required|min:6|max:20'
        ]);

        $data['password'] = Hash::make($data['password']);

        $user = new User($data);
        $user->save();

        return redirect()->route('users.index')->with('success', 'สร้างผู้ใช้งานใหม่สำเร็จ');
    }
}

resources/views/users/create.blade.php
@extends('layouts.template')

@section('content')
    <div class="container-fluid">
        <h4>สร้างผู้ใช้งาน</h4>

        <div class="row justify-content-center justify-content-md-start mt-2">
            <div class="col-md-6 col-11">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('users.store') }}" method="post" class="mt-4">
                            @csrf
                            <div class="card">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label>ชื่อ</label>
                                        <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name" value="{{ old('name') }}">
                                        @if($errors->has('name'))
                                            <span class="invalid-feedback">{{ $errors->first('name') }}</span>
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        <label>อีเมล</label>
                                        <input type="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" name="email" value="{{ old('email') }}">
                                        @if($errors->has('email'))
                                            <span class="invalid-feedback">{{ $errors->first('email') }}</span>
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        <label>รหัสผ่าน</label>
                                        <input type="password" class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}" name="password" value="{{ old('password') }}">
                                        @if($errors->has('password'))
                                            <span class="invalid-feedback">{{ $errors->first('password') }}</span>
                                        @endif
                                    </div>
                                </div>

                                <div class="card-footer d-flex justify-content-end">
                                    <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i><span class="ml-2">ยันยัน</span></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.template')

@section('content')

    <div class="container-fluid">

        <div class="d-flex justify-content-between">
            <div>
                <h4>รายการผู้ใข้งานระบบ</h4>
                <p>พบ {{ $users->total() }} ท่าน</p>
            </div>

            <div>
                @can('create', App\User::class)
                    <a href="{{ route('users.create') }}" class="btn btn-outline-primary">
                        <i class="fas fa-plus"></i>
                        <span>สร้างผู้ใช้งาน</span>
                    </a>
                @endcan
            </div>
        </div>

        <x-session-alert></x-session-alert>

        <div class="card mt-2">
            <table class="table">
                <thead>
                <tr>
                    <th>#ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Created At</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->getKey() }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->created_at->diffForHumans() }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <div class="card-footer d-flex justify-content-end">
                {!! $users->render() !!}
            </div>
        </div>
    </div>
@endsection