routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'register' => false,
]);

// Change password
Route::get('password-change', 'Auth\PasswordController@changePassword')->name('password.change');
Route::post('password-change', 'Auth\PasswordController@postChangePassword');

// Home page
Route::get('/', 'HomeController@index')->name('home');

// Product management
Route::resource('products', 'ProductController')->middleware('auth');

// Tracking
Route::resource('tracking', 'TrackingController')->middleware('auth');

// Control Panel
Route::resource('users', 'UserController')->middleware('auth');

// File holder
Route::post('files', 'FileController@store')->middleware('auth');


Route::get('reports/chart-quantity', 'ReportController@chartQuantity')->middleware('auth');
Route::get('reports/top-customers', 'ReportController@topCustomers')->middleware('auth');
Route::get('reports/top-products', 'ReportController@topProducts')->middleware('auth');

Route::get('reports/low-prod', 'ReportController@lowProdudct')->middleware('auth'); //ปั่น

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ route('home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                        @if(Auth::check())
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('products.index') }}">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('tracking.index') }}">Tracking</a>
                            </li>
                        @endif

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            @can('viewControlPanel')
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('users.index') }}">จัดการผู้ใข้งาน</a>
                                </li>
                            @endcan

                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('password.change') }}">
                                        เปลี่ยนรหัสผ่าน
                                    </a>

                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        ออกจากระบบ
                                    </a>


                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed ">

    <!-- begin:: Header Menu -->
    <button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
    <div class="kt-header-menu-wrapper" id="kt_header_menu_wrapper">
        <div id="kt_header_menu" class="kt-header-menu kt-header-menu-mobile  kt-header-menu--layout- ">
            <ul class="kt-menu__nav ">
            </ul>
        </div>
    </div>

    <!-- end:: Header Menu -->

    <!-- begin:: Header Topbar -->
    <div class="kt-header__topbar">

        <!--begin: Notifications -->




        <!--end: Quick Actions -->

        <!--begin:: Languages -->


        <!--end:: Languages -->

        <!--begin: User Bar -->
        <div class="kt-header__topbar-item kt-header__topbar-item--user">
            <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="0px,0px">

                <!--use "kt-rounded" class for rounded avatar style-->
                <div class="kt-header__topbar-user kt-rounded-">
                    <span class="kt-header__topbar-welcome kt-hidden-mobile">Hi,</span>
                    <span class="kt-header__topbar-username kt-hidden-mobile">{{ Auth::user()->name }}</span>
                    <img alt="Pic" src="{{ asset('assets/shell-logo.png') }}" class="kt-rounded-" />

                    <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
                    <span class="kt-badge kt-badge--username kt-badge--lg kt-badge--brand kt-hidden kt-badge--bold">S</span>
                </div>
            </div>

            <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-top-unround dropdown-menu-sm">
                <div class="kt-user-card kt-margin-b-40 kt-margin-b-30-tablet-and-mobile" style="background-image: url({{ asset('assets/media/misc/head_bg_sm.jpg') }})">
                    <div class="kt-user-card__wrapper">
                        <div class="kt-user-card__pic">

                            <!--use "kt-rounded" class for rounded avatar style-->
                            <img alt="Pic" src="{{ asset('assets/shell-logo.png') }}" class="kt-rounded-" />
                        </div>
                        <div class="kt-user-card__details">
                            <div class="kt-user-card__name">{{ Auth::user()->name }}</div>
                        </div>
                    </div>
                </div>
                <ul class="kt-nav kt-margin-b-10">
                    <li class="kt-nav__item">
                        <a href="{{ route('password.change') }}" class="kt-nav__link">
                            <span class="kt-nav__link-icon"><i class="flaticon2-gear"></i></span>
                            <span class="kt-nav__link-text">เปลี่ยนรหัสผ่าน</span>
                        </a>
                    </li>
                </ul>
                <ul class="kt-nav kt-margin-b-10">
                    <li class="kt-nav__custom kt-space-between">
                        <form action="{{ route('logout') }}" method="post">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-danger">ออกจากระบบ</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- end:: Header Topbar -->
</div>

resources/views/layouts/script.blade.php
<script src='{{asset('assets/plugins/global/plugins.bundle.js')}}'></script>
<script src='{{asset('assets/js/scripts.bundle.js')}}'></script>
<script src='{{asset('assets/plugins/custom/fullcalendar/fullcalendar.bundle.js')}}'></script>
<script src='{{asset('assets/js/pages/dashboard.js')}}'></script>
<script src="{{ mix('js/app.js') }}" defer></script>

resources/views/layouts/sidebar.blade.php
<div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid header_side" id="kt_aside_menu_wrapper" style="background-color: white">
    <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1" data-ktmenu-dropdown-timeout="500" style="background-color: #1f2433">
        <ul class="kt-menu__nav ">
            <li class="kt-menu__item  kt-menu__item--submenu kt-menu__item--open kt-menu__item--here" aria-haspopup="true" data-ktmenu-submenu-toggle="hover"><a href="{{ route('home') }}" class="kt-menu__link kt-menu__toggle"><i class="kt-menu__link-icon flaticon2-start-up"></i><span class="kt-menu__link-text">Dashboard</span></a>

            </li>
            <li class="kt-menu__item  kt-menu__item--submenu kt-menu__item--open kt-menu__item--here" aria-haspopup="true" data-ktmenu-submenu-toggle="hover"><a href="{{ route('products.index') }}" class="kt-menu__link kt-menu__toggle"><i class="kt-menu__link-icon flaticon2-list-2"></i><span class="kt-menu__link-text">Product</span></a>

            </li>

            <li class="kt-menu__item  kt-menu__item--submenu kt-menu__item--open kt-menu__item--here" aria-haspopup="true" data-ktmenu-submenu-toggle="hover"><a href="{{ route('tracking.index') }}" class="kt-menu__link kt-menu__toggle"><i class="kt-menu__link-icon flaticon2-position"></i><span class="kt-menu__link-text">Tracking</span></a>

            </li>

            @can('viewControlPanel')
                <li class="kt-menu__item  kt-menu__item--submenu kt-menu__item--open kt-menu__item--here" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('users.index') }}" class="kt-menu__link kt-menu__toggle">
                        <i class="kt-menu__link-icon flaticon2-position"></i>
                        <span class="kt-menu__link-text">จัดการผู้ใข้งาน</span>
                    </a>
                </li>
            @endcan
        </ul>
    </div>
</div>

resources/views/layouts/style.blade.php
<link href="{{asset('assets/plugins/custom/fullcalendar/fullcalendar.bundle.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/skins/header/base/light.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/skins/header/menu/light.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/skins/brand/navy.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/skins/aside/navy.css')}}" rel="stylesheet" type="text/css" />

<link href="{{asset('assets/plugins/custom/fullcalendar/fullcalendar.bundle.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/plugins/global/plugins.bundle.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/skins/brand/navy.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/skins/aside/navy.css')}}" rel="stylesheet" type="text/css" />

<link href="{{asset('assets/css/skins/aside/navy.css')}}" rel="stylesheet" type="text/css" />

<!--begin::Page Vendors Styles(used by this page) -->
<link href="{{asset('assets/plugins/global/plugins.bundle.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/style.bundle.css')}}" rel="stylesheet" type="text/css" />

<!--end::Page Vendors Styles -->


<link rel="stylesheet" href="{{ mix('css/app.css') }}" type="text/css">

resources/views/layouts/template.blade.php
<!DOCTYPE html>

<!--
Theme: Keen - The Ultimate Bootstrap Admin Theme
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
License: You must have a valid license purchased only from https://themes.getbootstrap.com/product/keen-the-ultimate-bootstrap-admin-theme/ in order to legally use the theme for your project.
-->
<html lang="en">

<!-- begin::Head -->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    @include('layouts.style')
</head>

<style>
    .header_side {
        background-color: white;!important;
    }
</style>

<!-- end::Head -->

<!-- begin::Body -->

<body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--fixed kt-subheader--enabled kt-subheader--solid kt-aside--enabled kt-aside--fixed kt-page--loading">

<!-- begin:: Header Mobile -->
<div id="app">
    <div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
        <div class="kt-header-mobile__logo">
            <a href="#">
                <img alt="Logo" src="{{ asset('/assets/logo-feyverly-co-ltd.jpg') }}" />
            </a>
        </div>
        <div class="kt-header-mobile__toolbar">
            <button class="kt-header-mobile__toolbar-toggler kt-header-mobile__toolbar-toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
            <button class="kt-header-mobile__toolbar-toggler" id="kt_header_mobile_toggler"><span></span></button>
            <button class="kt-header-mobile__toolbar-topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more"></i></button>
        </div>
    </div>

    <!-- end:: Header Mobile -->

    <!-- begin:: Root -->
    <div class="kt-grid kt-grid--hor kt-grid--root">

        <!-- begin:: Page -->
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">

            <!-- begin:: Aside -->
            <button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
            <div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

                <!-- begin::Aside Brand -->
                <div class="kt-aside__brand kt-grid__item header_side" id="kt_aside_brand">
                    <div class="kt-aside__brand-logo">
                        <a href="#">
                            <img alt="Logo" src="{{ asset('/assets/logo-feyverly-co-ltd.jpg') }}" style="max-height: 55px;"/>
                        </a>
                    </div>
                    <div class="kt-aside__brand-tools">
                        <button class="kt-aside__brand-aside-toggler kt-aside__brand-aside-toggler--left" id="kt_aside_toggler"><span></span></button>
                    </div>
                </div>

                <!-- end:: Aside Brand -->

                <!-- begin:: Aside Menu -->
                <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper" style="background-color: #1f2433">
                    @include("layouts.sidebar")
                </div>

            </div>

            <!-- end:: Aside -->

            <!-- begin:: Wrapper -->
            <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">

                <!-- begin:: Header -->
                @include("layouts.header")

                <!-- end:: Header -->
                <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

                    @yield('content')

                    <!-- end:: Content Head -->

                    <!-- begin:: Content -->
{{--                    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">--}}
{{--                        <div class="kt-portlet">--}}
{{--                            <div class="kt-portlet__body kt-portlet__body--fit">--}}
{{--                                <div class="kt-wizard-v3" id="kt_wizard_v3" data-ktwizard-state="step-first">--}}
{{--                                    @yield('content')--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}

                    <!-- end:: Content -->
                </div>

                <!-- begin:: Footer -->


                <!-- end:: Footer -->
            </div>

            <!-- end:: Wrapper -->
        </div>

        <!-- end:: Page -->
    </div>


    <!-- begin:: Quick Panel -->


    <!-- end:: Quick Panel -->

    <!-- begin::Scrolltop -->
    <div id="kt_scrolltop" class="kt-scrolltop">
        <i class="fa fa-arrow-up"></i>
    </div>


</div>
<!-- end::Demo Panel -->

<!-- begin::Global Config(global config for global JS sciprts) -->
<script>
    var KTAppOptions = {
        "colors": {
            "state": {
                "brand": "#5d78ff",
                "metal": "#c4c5d6",
                "light": "#ffffff",
                "accent": "#00c5dc",
                "primary": "#5867dd",
                "success": "#34bfa3",
                "info": "#36a3f7",
                "warning": "#ffb822",
                "danger": "#fd3995",
                "focus": "#9816f4"
            },
            "base": {
                "label": [
                    "#c5cbe3",
                    "#a1a8c3",
                    "#3d4465",
                    "#3e4466"
                ],
                "shape": [
                    "#f0f3ff",
                    "#d9dffa",
                    "#afb4d4",
                    "#646c9a"
                ]
            }
        }
    };
</script>



@include('layouts.script')

</body>

<!-- end::Body -->
</html>


<!--begin::Global Theme Bundle(used by all pages) -->
<script src="assets/plugins/global/plugins.bundle.js" type="text/javascript"></script>
<script src="assets/js/scripts.bundle.js" type="text/javascript"></script>